// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnYYvvR51LBEv43QZxSYcKPZEHOF8oTH4',
    appId: '1:662070410877:web:3e0ebb9891f336d58efb14',
    messagingSenderId: '662070410877',
    projectId: 'dailyease-f8296',
    authDomain: 'dailyease-f8296.firebaseapp.com',
    storageBucket: 'dailyease-f8296.firebasestorage.app',
    measurementId: 'G-H9QWS016GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzmY3-iyAPYguMIIaHe_YfMjUuoadEz-0',
    appId: '1:662070410877:android:8669532df01988eb8efb14',
    messagingSenderId: '662070410877',
    projectId: 'dailyease-f8296',
    storageBucket: 'dailyease-f8296.firebasestorage.app',
  );

}